In [1]:
import numpy as np

In [5]:
kanto = np.array([73,67,43])

In [6]:
kanto

array([73, 67, 43])

In [7]:
 weights = np.array([0.3,0.2,0.5])

In [8]:
weights

array([0.3, 0.2, 0.5])

In [9]:
type(kanto)

numpy.ndarray

In [10]:
type(weights)

numpy.ndarray

In [11]:
kanto[2]

43

In [12]:
weights[2]

0.5

## Operations on Numpy arrays

In [13]:
np.dot(kanto, weights)

56.8

In [14]:
(kanto * weights).sum()

56.8

In [15]:
kanto * weights

array([21.9, 13.4, 21.5])

In [16]:
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

In [17]:
array1 * array2

array([ 4, 10, 18])

In [18]:
array3 =array1 * array2

In [19]:
array3

array([ 4, 10, 18])

In [20]:
array3.sum()

32

In [21]:
array2.sum()

15

In [22]:
np.dot(array1, array2)

32

## Benefits of Numpy


In [23]:
a1 = [1,2,3,4]
a2 = [5,6,7,8]

a3 = np.array(a1)
a4 = np.array(a2)

In [24]:
type(a1)

list

In [25]:
type(a3)

numpy.ndarray

In [26]:
a3

array([1, 2, 3, 4])

In [27]:
a4

array([5, 6, 7, 8])

In [28]:
%%time
result = 0
for x1, x2 in zip(a1, a2):
    result += x1 * x2
result

Wall time: 0 ns


70

In [29]:
%%time
np.dot(a3,a4)

Wall time: 0 ns


70

In [30]:
a1 = list(range(1000000))
a2 = list(range(1000000))

a3 = np.array(a1)
a4 = np.array(a2)

In [31]:
%%time
result = 0
for x1, x2 in zip(a1, a2):
    result += x1 * x2
result

Wall time: 544 ms


333332833333500000

In [32]:
%%time
np.dot(a3, a4)

Wall time: 4.14 ms


584144992

In [33]:
a5 = a3 * a4

In [34]:
a5

array([         0,          1,          4, ..., -733379959, -731379964,
       -729379967])

In [35]:
a5.sum()

584144992

## Multidimensional Array

In [36]:
climate_data = np.array([[73,67,43],
                         [91,88,64],
                         [87,134,58],
                         [102,43,37],
                         [69, 96, 70]])

In [37]:
climate_data

array([[ 73,  67,  43],
       [ 91,  88,  64],
       [ 87, 134,  58],
       [102,  43,  37],
       [ 69,  96,  70]])

In [38]:
type(climate_data)

numpy.ndarray

In [39]:
climate_data.shape

(5, 3)

In [40]:
weights.shape

(3,)

In [41]:
kanto.shape

(3,)

In [42]:
 climate_data.dtype

dtype('int32')

In [43]:
weights.dtype

dtype('float64')

In [44]:
np.matmul(climate_data, weights)

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [45]:
climate_data @ weights

array([56.8, 76.9, 81.9, 57.7, 74.9])

In [47]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [48]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       [84., 63., 38.],
       [66., 50., 52.],
       [41., 94., 77.]])

In [49]:
climate_data.shape

(6, 3)

In [50]:
climate_data.dtype

dtype('float64')

In [52]:
help(np.genfromtxt)

Help on function genfromtxt in module numpy:

genfromtxt(fname, dtype=<class 'float'>, comments='#', delimiter=None, skip_header=0, skip_footer=0, converters=None, missing_values=None, filling_values=None, usecols=None, names=None, excludelist=None, deletechars=" !#$%&'()*+,-./:;<=>?@[\\]^{|}~", replace_space='_', autostrip=False, case_sensitive=True, defaultfmt='f%i', unpack=None, usemask=False, loose=True, invalid_raise=True, max_rows=None, encoding='bytes')
    Load data from a text file, with missing values handled as specified.
    
    Each line past the first `skip_header` lines is split at the `delimiter`
    character, and characters following the `comments` character are discarded.
    
    Parameters
    ----------
    fname : file, str, pathlib.Path, list of str, generator
        File, filename, list, or generator to read.  If the filename
        extension is `.gz` or `.bz2`, the file is first decompressed. Note
        that generators must return byte strings. The string

In [53]:
yields = np.matmul(climate_data, weights)

In [54]:
yields

array([72.2, 59.7, 65.2, 56.8, 55.8, 69.6])

In [55]:
yields.shape

(6,)

In [59]:
climate_results = np.concatenate((climate_data, yields.reshape(6,1)),axis=1)

In [60]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       [84. , 63. , 38. , 56.8],
       [66. , 50. , 52. , 55.8],
       [41. , 94. , 77. , 69.6]])

In [61]:
yields.reshape(6,1)

array([[72.2],
       [59.7],
       [65.2],
       [56.8],
       [55.8],
       [69.6]])

In [62]:
np.savetxt('climate_results.txt', climate_results, fmt='%.2f', header='temperature,rainfall,humidity,yields_apples',comments='')

In [66]:
climate_res = np.genfromtxt('climate_results.txt', delimiter=',', skip_header=1)

In [67]:
climate_res

array([nan, nan, nan, nan, nan, nan])

## Arithmetic Operations

In [68]:
a = np.arange(6)

In [69]:
a

array([0, 1, 2, 3, 4, 5])

In [70]:
arr1 = np.random.randint(1,10, size=(3,4))

In [71]:
arr1

array([[4, 2, 1, 7],
       [2, 4, 3, 4],
       [6, 2, 1, 1]])

In [72]:
arr2 = np.random.randint(11,20,size=(3,4))

In [73]:
arr2

array([[16, 19, 18, 18],
       [13, 15, 15, 16],
       [18, 18, 15, 17]])

In [74]:
arr1 + 3

array([[ 7,  5,  4, 10],
       [ 5,  7,  6,  7],
       [ 9,  5,  4,  4]])

In [75]:
arr2 + 2

array([[18, 21, 20, 20],
       [15, 17, 17, 18],
       [20, 20, 17, 19]])

In [76]:
arr1 - arr2

array([[-12, -17, -17, -11],
       [-11, -11, -12, -12],
       [-12, -16, -14, -16]])

In [77]:
arr2 - arr1

array([[12, 17, 17, 11],
       [11, 11, 12, 12],
       [12, 16, 14, 16]])

In [78]:
arr1 + arr2

array([[20, 21, 19, 25],
       [15, 19, 18, 20],
       [24, 20, 16, 18]])

In [79]:
arr1 / 2

array([[2. , 1. , 0.5, 3.5],
       [1. , 2. , 1.5, 2. ],
       [3. , 1. , 0.5, 0.5]])

In [80]:
arr1 % 2

array([[0, 0, 1, 1],
       [0, 0, 1, 0],
       [0, 0, 1, 1]], dtype=int32)

In [81]:
arr3 = np.random.randint(1,4,size=(3,4))

In [82]:
arr3

array([[3, 1, 1, 2],
       [1, 1, 1, 3],
       [3, 2, 3, 1]])

In [83]:
arr4 = np.array([1,2,3,4])

In [84]:
arr3 + arr4

array([[4, 3, 4, 6],
       [2, 3, 4, 7],
       [4, 4, 6, 5]])

In [85]:
arr5 = np.array([[1,2,3],
                 [3,4,5]])
arr6 = np.array([[2,2,3],
                 [1,2,5]])

In [86]:
arr5 == arr6

array([[False,  True,  True],
       [False, False,  True]])

In [87]:
arr5 != arr6

array([[ True, False, False],
       [ True,  True, False]])

In [88]:
arr5 >= arr6

array([[False,  True,  True],
       [ True,  True,  True]])

In [89]:
arr5 <= arr6

array([[ True,  True,  True],
       [False, False,  True]])

In [90]:
(arr5 == arr6).sum()

3

In [91]:
arr3 = np.array([
    [[11,12,13,14],
     [13,14,15,19]],
    [[15,16,17,21],
     [63,92,36,18]],
    [[98,32,81,23],
     [17,18,19.5,43]]
])

In [92]:
arr3.shape

(3, 2, 4)

In [93]:
arr3[1,1,1]

92.0

In [95]:
arr3[2,0,2]

81.0

In [96]:
arr3.dtype

dtype('float64')

In [97]:
arr3[1]

array([[15., 16., 17., 21.],
       [63., 92., 36., 18.]])

In [98]:
arr3[1,1]

array([63., 92., 36., 18.])

In [99]:
arr3[1,1,3]

18.0

In [101]:
arr3[1,1,2]

36.0

In [106]:
arr3[1:, 0:1, :2]

array([[[15., 16.]],

       [[98., 32.]]])

In [108]:
arr3[1:, 1, :3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [109]:
arr3

array([[[11. , 12. , 13. , 14. ],
        [13. , 14. , 15. , 19. ]],

       [[15. , 16. , 17. , 21. ],
        [63. , 92. , 36. , 18. ]],

       [[98. , 32. , 81. , 23. ],
        [17. , 18. , 19.5, 43. ]]])

In [111]:
arr3[0,0,2]

13.0

In [114]:
arr3[0:, 1, :4]

array([[13. , 14. , 15. , 19. ],
       [63. , 92. , 36. , 18. ],
       [17. , 18. , 19.5, 43. ]])

In [117]:
arr3[1:, 1,3]

array([18., 43.])

## Other way to create arrays

In [118]:
np.zeros(3)

array([0., 0., 0.])

In [121]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [122]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [123]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [124]:
help(np.random.random)

Help on built-in function random:

random(...) method of numpy.random.mtrand.RandomState instance
    random(size=None)
    
    Return random floats in the half-open interval [0.0, 1.0). Alias for
    `random_sample` to ease forward-porting to the new random API.



In [126]:
np.random.randint(1,4,size=(2,2))

array([[2, 1],
       [3, 2]])

In [127]:
np.random.rand(5)

array([0.05468855, 0.77546325, 0.98410655, 0.09649559, 0.5898694 ])

In [128]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [129]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [130]:
np.random.randn(2,3)

array([[-0.79433856,  0.63063671,  0.84051647],
       [ 0.8835619 ,  2.34277726, -0.25773633]])

In [131]:
np.full((2,3), 24)

array([[24, 24, 24],
       [24, 24, 24]])

In [134]:
np.arange(10,91,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90])

In [136]:
np.linspace(10,20,10)

array([10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444,
       15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ])

In [140]:
np.arange(10,90,2).reshape(2,2,10)

array([[[10, 12, 14, 16, 18, 20, 22, 24, 26, 28],
        [30, 32, 34, 36, 38, 40, 42, 44, 46, 48]],

       [[50, 52, 54, 56, 58, 60, 62, 64, 66, 68],
        [70, 72, 74, 76, 78, 80, 82, 84, 86, 88]]])

In [141]:
arr1 = [[1,2],
       [3,4.0]]

arr2 = [[5,6,7],
        [8,9,10]]

In [142]:
arr3 = np.concatenate((arr1,arr2),axis=1)

In [143]:
arr3

array([[ 1.,  2.,  5.,  6.,  7.],
       [ 3.,  4.,  8.,  9., 10.]])

In [144]:
help(np.empty)

Help on built-in function empty in module numpy:

empty(...)
    empty(shape, dtype=float, order='C')
    
    Return a new array of given shape and type, without initializing entries.
    
    Parameters
    ----------
    shape : int or tuple of int
        Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        Desired output data-type for the array, e.g, `numpy.int8`. Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: 'C'
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of uninitialized (arbitrary) data of the given shape, dtype, and
        order.  Object arrays will be initialized to None.
    
    See Also
    --------
    empty_like : Return an empty array with shape and type of input.
    ones : Return a new array setting values to one.
    zeros : Return a new array 

In [146]:
np.empty((2,2))

array([[1., 2.],
       [3., 4.]])

In [149]:
np.empty((5,6))

array([[9.38079535e-312, 9.78249979e-322, 0.00000000e+000,
        0.00000000e+000, 0.00000000e+000, 5.02034658e+175],
       [4.00385792e+174, 5.39575688e-062, 4.11581875e+179,
        1.43727019e-051, 1.14420182e-071, 3.59751658e+252],
       [8.93185432e+271, 7.33723594e+223, 1.47763641e+248,
        1.16096346e-028, 7.69165785e+218, 1.35617292e+248],
       [3.52610177e-057, 2.36778818e+179, 1.34940491e+161,
        5.22194281e-037, 5.82653703e-144, 1.16097020e-028],
       [3.93230079e-062, 2.73785005e-052, 1.24635843e-047,
        1.11763122e+261, 1.16318408e-028, 2.62459060e-306]])

In [2]:
import numpy as np
arr = np.array([[13. , 14. , 15. , 19.],
                [63. , 92. , 36. , 18. ],
                [17. , 18. , 19.5, 43. ]])

In [3]:
arr.shape

(3, 4)

In [4]:
arr.dtype

dtype('float64')

In [5]:
arr.ndim

2

In [8]:
np.linspace(10,20,5)

array([10. , 12.5, 15. , 17.5, 20. ])

In [1]:
import numpy as np

In [2]:
arr = np.array([[13. , 14. , 15. , 19.],
                [63. , 92. , 36. , 18. ],
                [17. , 18. , 19.5, 43. ]])

In [3]:
arr[1]

array([63., 92., 36., 18.])

In [4]:
arr[1:,:3]

array([[63. , 92. , 36. ],
       [17. , 18. , 19.5]])

In [7]:
arr[1:2,0:4:2]

array([[63., 36.]])

In [10]:
arr[1:2, 0] = 64.0

In [11]:
arr

array([[13. , 14. , 15. , 19. ],
       [64. , 92. , 36. , 18. ],
       [17. , 18. , 19.5, 43. ]])

In [12]:
b = np.array([[[1,2], [3,4]],[[5,6],[7,8]]])

In [13]:
b

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [14]:
b.shape

(2, 2, 2)

In [15]:
b.dtype

dtype('int32')

In [16]:
b.itemsize

4

In [17]:
b.size

8

In [24]:
b[0:,1:, :] = [[[8,8]],
               [[8,8]]]

In [25]:
b

array([[[1, 2],
        [8, 8]],

       [[5, 6],
        [8, 8]]])